version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: leonardo
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: persondb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ms01-consumer-db:
    build: ./ms01-consumer-db
    depends_on:
      - kafka
      - postgres

  ms02-transform-timestamp:
    build: ./ms02-transform-timestamp
    depends_on:
      - kafka

  ms05-xml-reader:
    build: ./ms05-xml-reader
    depends_on:
      - kafka
    volumes:
      - ./ms05-xml-reader/xml-testing:/app/xml-testing

  ms04-rest-api:
    build: ./ms04-rest-api
    ports:
      - "8084:8084"
    depends_on:
      - kafka
      - postgres

volumes:
  postgres_data:
